### ISSUE TITLE
Replace JSON with YAML

### ISSUE THREAD

**Issue by rodrigo-ceccato** [phd-artifacts/spinner#13]
Title. Its more human...

Possible configuration:
```YAML
# Metadata about the benchmarks
metadata:
  description: "I/O benchmarks"
  version: "1.0"
  runs: 30
  timeout: 600
  input_file: "random_numbers.bin"

# Common build settings
common_build:
  cmake_flags:
    - "-DCMAKE_BUILD_TYPE=Release"
  make_flags:
    - "-j"
  omp_env:
    CC: "gcc"
    CXX: "g++"
  mpi_env:
    CC: "mpicc"
    CXX: "mpicxx"

# Task-specific configurations
tasks:
  omp-tasks:
    build:
      env: *omp_env
      path: "benchs/omp-tasks"
    command_template: "./omp-tasks -n {{tasks}} -r {{read_step}} -i {{input_file}}"
    parameters:
      tasks: [1]
      read_step: [100]

  mpi-io:
    build:
      env: *mpi_env
      path: "benchs/mpi-io"
    command_template: "mpirun -np {{procs}} ./mpi-io -n {{nodes}} -r {{read_step}} -i {{input_file}}"
    parameters:
      nodes: [1]
      procs: [1]
      read_step: [100]

```
